---
{%- import 'macros/tag-release.yaml' as tag_release %}

# TODO:
#   - Make rendered yaml pretty! It's all over the place right now.
#   - Can we use pyyaml instead of jinja2 to generate these configs?

resources:
  - name: busywork
    type: git
    source:
      uri: https://github.com/qiime2/busywork
      branch: madmin
      #paths:
      #  - current-dev-release

  {%- for project in projects %}
  - name: {{ project.name }}-source
    type: git
    source:
      uri: https://github.com/{{ project.github_org }}/{{ project.name }}
      branch: {{ project.release_branch }}
      {%- if project.tag %}
      tag: {{ project.tag }}
      {%- endif %}

  - name: {{ project.name }}-gh-release
    type: github-release
    source:
      owner: {{ project.github_org }}
      repository: {{ project.name }}
      {%- raw %}
      access_token: {{github_token}}
      {%- endraw %}
      release: false
      pre_release: true
      drafts: false
  {%- endfor %}

jobs:
  - name: tag-release
    plan:
      - get: busywork
      {%- for project in projects %}
      - get: {{ project.name }}-source
      {%- endfor %}
      - task: tag-release
        config:
          {{- tag_release.make_config(projects)|indent(10) }}
      {%- for project in projects %}
      - put: {{ project.name }}-gh-release
        params:
          name: {{ project.name }}-gh-release/name
          tag: {{ project.name }}-gh-release/tag
      {%- endfor %}
