---
{%- import 'macros/tag-dev.yaml' as tag_dev %}

# TODO:
#   - Make rendered yaml pretty! It's all over the place right now.
#   - Can we use pyyaml instead of jinja2 to generate these configs?

resources:
  - name: busywork
    type: git
    source:
      uri: https://github.com/qiime2/busywork
      branch: madmin

  # TODO: serial_groups?
  - name: current-dev-release
    type: git
    source:
      uri: https://github.com/qiime2/busywork
      branch: madmin
      paths:
        - current-dev-release

  {%- for project in projects %}
  - name: {{ project.name }}-source
    type: git
    source:
      uri: https://github.com/{{ project.github_org }}/{{ project.name }}
      branch: {{ project.release_branch }}
      {%- raw %}
      username: {{github_user}}
      password: {{github_pass}}
      {%- endraw %}
  {%- endfor %}

jobs:
  - name: tag-release
    plan:
      - get: busywork
      {%- for project in projects %}
      - get: {{ project.name }}-source
      {%- endfor %}
      - task: tag-release
        config:
          {{- tag_release.make_config(projects)|indent(10) }}
      {%- for project in projects %}
      - put: {{ project.name }}-source
        params:
          repository: tagged-{{ project.name }}-source
          # TODO: is this really necessary?!
          tag: tagged-{{ project.name }}-source/tag
          annotate: annotate
      {%- endfor %}
  - name: tag-dev
    plan:
      - get: current-dev-release
        trigger: true
      {%- for project in projects %}
      - get: {{ project.name }}-source
      {%- endfor %}
      - task: tag-dev
        config:
          {{- tag_dev.make_config(projects)|indent(10) }}
      {%- for project in projects %}
      - put: {{ project.name }}-source
        params:
          repository: tagged-{{ project.name }}-source
          # TODO: is this really necessary?!
          tag: tagged-{{ project.name }}-source/tag
          annotate: annotate
      {%- endfor %}
