---
groups:
  - name: build
    jobs:
      - build-qiime2
      - build-q2cli
      - build-q2templates
      - build-q2-types
      - build-q2-feature-table
  - name: deploy
    jobs:
      - integration
      - upload-qiime2
      - upload-q2cli
      - upload-q2templates
      - upload-q2-types
      - upload-q2-feature-table

resource_types:
  - name: conda-channel
    type: docker-image
    source:
      repository: qiime2/conda-channel-resource

resources:
  - name: busywork
    type: git
    source:
      uri: https://github.com/qiime2/busywork
      branch: madmin

  - name: nightly
    type: time
    source:
      start: 12:00 AM
      stop: 1:00 AM
      location: America/Phoenix

  - name: qiime2-source
    type: git
    source:
      uri: https://github.com/nervous-laughter/qiime2
      branch: master

  - name: q2cli-source
    type: git
    source:
      uri: https://github.com/nervous-laughter/q2cli
      branch: master

  - name: q2templates-source
    type: git
    source:
      uri: https://github.com/nervous-laughter/q2templates
      branch: master

  - name: q2-types-source
    type: git
    source:
      uri: https://github.com/nervous-laughter/q2-types
      branch: master

  - name: q2-feature-table-source
    type: git
    source:
      uri: https://github.com/nervous-laughter/q2-feature-table
      branch: master

  - name: qiime2-channel
    type: conda-channel
    source:
      pkg_name: qiime2
      uri: {{ftp_uri}}
      channel: {{ftp_channel_root}}
      user: {{ftp_user}}
      pass: {{ftp_pass}}

  - name: q2cli-channel
    type: conda-channel
    source:
      pkg_name: q2cli
      uri: {{ftp_uri}}
      channel: {{ftp_channel_root}}
      user: {{ftp_user}}
      pass: {{ftp_pass}}

  - name: q2templates-channel
    type: conda-channel
    source:
      pkg_name: q2templates
      uri: {{ftp_uri}}
      channel: {{ftp_channel_root}}
      user: {{ftp_user}}
      pass: {{ftp_pass}}

  - name: q2-types-channel
    type: conda-channel
    source:
      pkg_name: q2-types
      uri: {{ftp_uri}}
      channel: {{ftp_channel_root}}
      user: {{ftp_user}}
      pass: {{ftp_pass}}

  - name: q2-feature-table-channel
    type: conda-channel
    source:
      pkg_name: q2-feature-table
      uri: {{ftp_uri}}
      channel: {{ftp_channel_root}}
      user: {{ftp_user}}
      pass: {{ftp_pass}}

# TODO make channel puts serial (use pool resource for locking)
jobs:
  - name: build-qiime2
    plan:
      - get: busywork
      - get: qiime2-source
        trigger: true
      - task: build-qiime2
        file: busywork/ci/master/tasks/build-qiime2.yaml
      - aggregate:
        - task: test-qiime2-linux
          file: busywork/ci/master/tasks/test-qiime2-linux.yaml
        - task: test-qiime2-darwin
          file: busywork/ci/master/tasks/test-qiime2-darwin.yaml
      - put: qiime2-channel
        params:
          from: builds

  - name: build-q2cli
    plan:
      - get: busywork
      - get: q2cli-source
        trigger: true
      - get: qiime2-channel
        trigger: true
      - aggregate:
        - do:
          - task: build-q2cli-linux
            file: busywork/ci/master/tasks/build-q2cli-linux.yaml
          - task: test-q2cli-linux
            file: busywork/ci/master/tasks/test-q2cli-linux.yaml
        - do:
          - task: build-q2cli-darwin
            file: busywork/ci/master/tasks/build-q2cli-darwin.yaml
          - task: test-q2cli-darwin
            file: busywork/ci/master/tasks/test-q2cli-darwin.yaml
      - put: q2cli-channel
        params:
          from: builds

  - name: build-q2templates
    plan:
      - get: busywork
      - get: q2templates-source
        trigger: true
      - task: build-q2templates
        file: busywork/ci/master/tasks/build-q2templates.yaml
      # NOTE: there currently are no tests for q2templates
      - put: q2templates-channel
        params:
          from: builds

  - name: build-q2-types
    plan:
      - get: busywork
      - get: q2-types-source
        trigger: true
      - get: qiime2-channel
        trigger: true
      - task: build-q2-types
        file: busywork/ci/master/tasks/build-q2-types.yaml
      - aggregate:
        - task: test-q2-types-linux
          file: busywork/ci/master/tasks/test-q2-types-linux.yaml
        - task: test-q2-types-darwin
          file: busywork/ci/master/tasks/test-q2-types-darwin.yaml
      - put: q2-types-channel
        params:
          from: builds

  - name: build-q2-feature-table
    plan:
      - get: busywork
      - get: q2-feature-table-source
        trigger: true
      - get: qiime2-channel
        trigger: true
      - get: q2templates-channel
        trigger: true
      - get: q2-types-channel
        trigger: true
      - task: build-q2-feature-table
        file: busywork/ci/master/tasks/build-q2-feature-table.yaml
      - aggregate:
        - task: test-q2-feature-table-linux
          file: busywork/ci/master/tasks/test-q2-feature-table-linux.yaml
        - task: test-q2-feature-table-darwin
          file: busywork/ci/master/tasks/test-q2-feature-table-darwin.yaml
      - put: q2-feature-table-channel
        params:
          from: builds

  - name: integration
    plan:
      - get: busywork
      - get: nightly
        trigger: true
      - get: qiime2-channel
        trigger: true
      - get: q2cli-channel
        trigger: true
      - get: q2templates-channel
        trigger: true
      - get: q2-types-channel
        trigger: true
      - get: q2-feature-table-channel
        trigger: true
      - aggregate:
        - task: integration-linux
          file: busywork/ci/master/tasks/integration-linux.yaml
        - task: integration-darwin
          file: busywork/ci/master/tasks/integration-darwin.yaml

  - name: upload-qiime2
    plan:
      - get: qiime2-channel
        trigger: true
        passed:
          - integration

  - name: upload-q2cli
    plan:
      - get: q2cli-channel
        trigger: true
        passed:
          - integration

  - name: upload-q2templates
    plan:
      - get: q2templates-channel
        trigger: true
        passed:
          - integration

  - name: upload-q2-types
    plan:
      - get: q2-types-channel
        trigger: true
        passed:
          - integration

  - name: upload-q2-feature-table
    plan:
      - get: q2-feature-table-channel
        trigger: true
        passed:
          - integration
