---
groups:
  - name: build
    jobs:
      - build-qiime2
      - build-q2cli
      - build-q2templates
      - build-q2-types
      - build-q2-feature-table
      - build-q2-alignment
  - name: test
    jobs:
      - unit-test-qiime2
      - unit-test-q2cli
      - unit-test-q2-types
      - unit-test-q2-feature-table
      - unit-test-q2-alignment
      - integration
  - name: deploy
    jobs:
      - upload-qiime2
      - upload-q2cli
      - upload-q2templates
      - upload-q2-types
      - upload-q2-feature-table
      - upload-q2-alignment

resource_types:
  - name: conda-channel
    type: docker-image
    source:
      repository: qiime2/conda-channel-resource

resources:
  - name: busywork
    type: git
    source:
      uri: https://github.com/qiime2/busywork
      branch: madmin

  - name: nightly
    type: time
    source:
      start: 12:00 AM
      stop: 1:00 AM
      location: America/Phoenix

  - name: qiime2-source
    type: git
    source:
      uri: https://github.com/nervous-laughter/qiime2
      branch: master

  - name: q2cli-source
    type: git
    source:
      uri: https://github.com/nervous-laughter/q2cli
      branch: master

  - name: q2templates-source
    type: git
    source:
      uri: https://github.com/nervous-laughter/q2templates
      branch: master

  - name: q2-types-source
    type: git
    source:
      uri: https://github.com/nervous-laughter/q2-types
      branch: master

  - name: q2-feature-table-source
    type: git
    source:
      uri: https://github.com/nervous-laughter/q2-feature-table
      branch: master

  - name: q2-alignment-source
    type: git
    source:
      uri: https://github.com/nervous-laughter/q2-alignment
      branch: master

  - name: qiime2-channel
    type: conda-channel
    source:
      pkg_name: qiime2
      uri: {{ftp_uri}}
      channel: {{ftp_channel_root}}
      user: {{ftp_user}}
      pass: {{ftp_pass}}

  - name: q2cli-channel
    type: conda-channel
    source:
      pkg_name: q2cli
      uri: {{ftp_uri}}
      channel: {{ftp_channel_root}}
      user: {{ftp_user}}
      pass: {{ftp_pass}}

  - name: q2templates-channel
    type: conda-channel
    source:
      pkg_name: q2templates
      uri: {{ftp_uri}}
      channel: {{ftp_channel_root}}
      user: {{ftp_user}}
      pass: {{ftp_pass}}

  - name: q2-types-channel
    type: conda-channel
    source:
      pkg_name: q2-types
      uri: {{ftp_uri}}
      channel: {{ftp_channel_root}}
      user: {{ftp_user}}
      pass: {{ftp_pass}}

  - name: q2-feature-table-channel
    type: conda-channel
    source:
      pkg_name: q2-feature-table
      uri: {{ftp_uri}}
      channel: {{ftp_channel_root}}
      user: {{ftp_user}}
      pass: {{ftp_pass}}

  - name: q2-alignment-channel
    type: conda-channel
    source:
      pkg_name: q2-alignment
      uri: {{ftp_uri}}
      channel: {{ftp_channel_root}}
      user: {{ftp_user}}
      pass: {{ftp_pass}}

jobs:
  - name: build-qiime2
    plan:
      - get: busywork
      - get: qiime2-source
        trigger: true
      - aggregate:
        - task: build-linux
          file: busywork/ci/master/tasks/build-linux.yaml
          config:
            inputs:
              - name: busywork
              - name: qiime2-source
                path: source
        - task: build-darwin
          file: busywork/ci/master/tasks/build-darwin.yaml
          config:
            inputs:
              - name: busywork
              - name: qiime2-source
                path: source
      - task: merge-channels
        file: busywork/ci/master/tasks/merge-channels.yaml
      - put: qiime2-channel
        params:
          from: builds

  - name: unit-test-qiime2
    plan:
      - get: busywork
      - get: qiime2-channel
        trigger: true
        passed: [build-qiime2]
      - aggregate:
        - task: test-linux
          file: busywork/ci/master/tasks/test-linux.yaml
          params:
            - PKG_NAME: qiime2
            - QIIMETEST: 1
            - TEST_RUNNER_CMD: nosetests qiime2
          config:
            inputs:
              - name: busywork
              - name: qiime2-channel
        - task: test-darwin
          file: busywork/ci/master/tasks/test-darwin.yaml
          params:
            - PKG_NAME: qiime2
            - QIIMETEST: 1
            - TEST_RUNNER_CMD: nosetests qiime2
          config:
            inputs:
              - name: busywork
              - name: qiime2-channel

  - name: build-q2cli
    plan:
      - get: busywork
      - get: q2cli-source
        trigger: true
      - get: qiime2-channel
        passed: [unit-test-qiime2]
      - aggregate:
        - task: build-linux
          file: busywork/ci/master/tasks/build-linux.yaml
          config:
            inputs:
              - name: busywork
              - name: q2cli-source
                path: source
              - name: qiime2-channel
        - task: build-darwin
          file: busywork/ci/master/tasks/build-darwin.yaml
          config:
            inputs:
              - name: busywork
              - name: q2cli-source
                path: source
              - name: qiime2-channel
      - task: merge-channels
        file: busywork/ci/master/tasks/merge-channels.yaml
      - put: q2cli-channel
        params:
          from: builds

  - name: unit-test-q2cli
    plan:
      - get: busywork
      - get: q2cli-channel
        trigger: true
        passed: [build-q2cli]
      - get: qiime2-channel
        trigger: true
        passed: [unit-test-qiime2]
      - aggregate:
        - task: test-linux
          file: busywork/ci/master/tasks/test-linux.yaml
          params:
            - PKG_NAME: q2cli
            - QIIMETEST: 1
            - TEST_RUNNER_CMD: nosetests q2cli
          config:
            inputs:
              - name: busywork
              - name: q2cli-channel
              - name: qiime2-channel
        - task: test-darwin
          file: busywork/ci/master/tasks/test-darwin.yaml
          params:
            - PKG_NAME: q2cli
            - QIIMETEST: 1
            - TEST_RUNNER_CMD: nosetests q2cli
          config:
            inputs:
              - name: busywork
              - name: q2cli-channel
              - name: qiime2-channel

  - name: build-q2templates
    plan:
      - get: busywork
      - get: q2templates-source
        trigger: true
      - aggregate:
        - task: build-linux
          file: busywork/ci/master/tasks/build-linux.yaml
          config:
            inputs:
              - name: busywork
              - name: q2templates-source
                path: source
        - task: build-darwin
          file: busywork/ci/master/tasks/build-darwin.yaml
          config:
            inputs:
              - name: busywork
              - name: q2templates-source
                path: source
      - task: merge-channels
        file: busywork/ci/master/tasks/merge-channels.yaml
      - put: q2templates-channel
        params:
          from: builds

  # TODO: Test q2templates someday

  - name: build-q2-types
    plan:
      - get: busywork
      - get: q2-types-source
        trigger: true
        name: source
      - get: qiime2-channel
        passed: [unit-test-qiime2]
      - aggregate:
        - task: build-linux
          file: busywork/ci/master/tasks/build-linux.yaml
          config:
            inputs:
              - name: busywork
              - name: q2-types-source
                path: source
              - name: qiime2-channel
        - task: build-darwin
          file: busywork/ci/master/tasks/build-darwin.yaml
          config:
            inputs:
              - name: busywork
              - name: q2-types-source
                path: source
              - name: qiime2-channel
      - task: merge-channels
        file: busywork/ci/master/tasks/merge-channels.yaml
      - put: q2-types-channel
        params:
          from: builds

  - name: unit-test-q2-types
    plan:
      - get: busywork
      - get: q2-types-channel
        trigger: true
        passed: [build-q2-types]
      - get: qiime2-channel
        trigger: true
        passed: [unit-test-qiime2]
      - aggregate:
        - task: test-linux
          file: busywork/ci/master/tasks/test-linux.yaml
          params:
            PKG_NAME: q2-types
            TEST_RUNNER_CMD: py.test --pyargs q2_types
          config:
            inputs:
              - name: busywork
              - name: q2-types-channel
              - name: qiime2-channel
        - task: test-darwin
          file: busywork/ci/master/tasks/test-darwin.yaml
          params:
            PKG_NAME: q2-types
            TEST_RUNNER_CMD: py.test --pyargs q2_types
          config:
            inputs:
              - name: busywork
              - name: q2-types-channel
              - name: qiime2-channel

  - name: build-q2-feature-table
    plan:
      - get: busywork
      - get: q2-feature-table-source
        trigger: true
      - get: qiime2-channel
        trigger: true
        passed: [unit-test-qiime2]
      - get: q2templates-channel
        trigger: true
      - get: q2-types-channel
        trigger: true
        passed: [unit-test-q2-types]
      - aggregate:
        - task: build-linux
          file: busywork/ci/master/tasks/build-linux.yaml
          config:
            inputs:
              - name: busywork
              - name: q2-feature-table-source
                path: source
              - name: qiime2-channel
              - name: q2templates-channel
              - name: q2-types-channel
        - task: build-darwin
          file: busywork/ci/master/tasks/build-darwin.yaml
          config:
            inputs:
              - name: busywork
              - name: q2-feature-table-source
                path: source
              - name: qiime2-channel
              - name: q2templates-channel
              - name: q2-types-channel
      - task: merge-channels
        file: busywork/ci/master/tasks/merge-channels.yaml
      - put: q2-feature-table-channel
        params:
          from: builds

  - name: unit-test-q2-feature-table
    plan:
      - get: busywork
      - get: q2-feature-table-channel
        trigger: true
        passed: [build-q2-feature-table]
      - get: qiime2-channel
        trigger: true
        passed: [unit-test-qiime2]
      - get: q2templates-channel
        trigger: true
      - get: q2-types-channel
        trigger: true
        passed: [unit-test-q2-types]
      - aggregate:
        - task: test-linux
          file: busywork/ci/master/tasks/test-linux.yaml
          params:
            PKG_NAME: q2-feature-table
            TEST_RUNNER_CMD: py.test --pyargs q2_feature_table
          config:
            inputs:
              - name: busywork
              - name: q2-feature-table-channel
              - name: qiime2-channel
              - name: q2templates-channel
              - name: q2-types-channel
        - task: test-darwin
          file: busywork/ci/master/tasks/test-darwin.yaml
          params:
            PKG_NAME: q2-feature-table
            TEST_RUNNER_CMD: py.test --pyargs q2_feature_table
          config:
            inputs:
              - name: busywork
              - name: q2-feature-table-channel
              - name: qiime2-channel
              - name: q2templates-channel
              - name: q2-types-channel

  - name: build-q2-alignment
    plan:
      - get: busywork
      - get: q2-alignment-source
        trigger: true
      - get: qiime2-channel
        trigger: true
        passed: [unit-test-qiime2]
      - get: q2-types-channel
        trigger: true
        passed: [unit-test-q2-types]
      - aggregate:
        - task: build-linux
          file: busywork/ci/master/tasks/build-linux.yaml
          config:
            inputs:
              - name: busywork
              - name: q2-alignment-source
                path: source
              - name: qiime2-channel
              - name: q2-types-channel
        - task: build-darwin
          file: busywork/ci/master/tasks/build-darwin.yaml
          config:
            inputs:
              - name: busywork
              - name: q2-alignment-source
                path: source
              - name: qiime2-channel
              - name: q2-types-channel
      - task: merge-channels
        file: busywork/ci/master/tasks/merge-channels.yaml
      - put: q2-alignment-channel
        params:
          from: builds

  - name: unit-test-q2-alignment
    plan:
      - get: busywork
      - get: q2-alignment-channel
        trigger: true
        passed: [build-q2-alignment]
      - get: qiime2-channel
        trigger: true
        passed: [unit-test-qiime2]
      - get: q2-types-channel
        trigger: true
        passed: [unit-test-q2-types]
      - aggregate:
        - task: test-linux
          file: busywork/ci/master/tasks/test-linux.yaml
          params:
            PKG_NAME: q2-alignment
            TEST_RUNNER_CMD: py.test --pyargs q2_alignment
          config:
            inputs:
              - name: busywork
              - name: q2-alignment-channel
              - name: qiime2-channel
              - name: q2-types-channel
        - task: test-darwin
          file: busywork/ci/master/tasks/test-darwin.yaml
          params:
            PKG_NAME: q2-alignment
            TEST_RUNNER_CMD: py.test --pyargs q2_alignment
          config:
            inputs:
              - name: busywork
              - name: q2-alignment-channel
              - name: qiime2-channel
              - name: q2-types-channel

  - name: integration
    plan:
      - get: busywork
      - get: nightly
        trigger: true
      - get: qiime2-channel
        trigger: true
        passed: [unit-test-qiime2]
      - get: q2cli-channel
        trigger: true
        passed: [unit-test-q2cli]
      - get: q2templates-channel
        trigger: true
      - get: q2-types-channel
        trigger: true
        passed: [unit-test-q2-types]
      - get: q2-feature-table-channel
        trigger: true
        passed: [unit-test-q2-feature-table]
      - get: q2-alignment-channel
        trigger: true
        passed: [unit-test-q2-alignment]
      - aggregate:
        - task: integration-linux
          file: busywork/ci/master/tasks/integration-linux.yaml
        - task: integration-darwin
          file: busywork/ci/master/tasks/integration-darwin.yaml

  - name: upload-qiime2
    plan:
      - get: qiime2-channel
        trigger: true
        passed: [integration]

  - name: upload-q2cli
    plan:
      - get: q2cli-channel
        trigger: true
        passed: [integration]

  - name: upload-q2templates
    plan:
      - get: q2templates-channel
        trigger: true
        passed: [integration]

  - name: upload-q2-types
    plan:
      - get: q2-types-channel
        trigger: true
        passed: [integration]

  - name: upload-q2-feature-table
    plan:
      - get: q2-feature-table-channel
        trigger: true
        passed: [integration]

  - name: upload-q2-alignment
    plan:
      - get: q2-alignment-channel
        trigger: true
        passed: [integration]
