---
platform: linux

image_resource:
  type: docker-image
  source:
    repository: continuumio/miniconda3
    version: latest

inputs:
  - name: busywork
  - name: docs-source
  - name: conda-env

run:
  path: busywork/ci/master/tasks/integration.sh
