---
platform: linux

image_resource:
  type: docker-image
  source:
    repository: continuumio/miniconda3
    version: latest

params:
  - TEST_RUNNER_CMD:

inputs:
  - name: busywork
  - name: q2-types-channel
  - name: qiime2-channel

run:
  path: busywork/ci/master/tasks/test.sh
