---
platform: linux

image_resource:
  type: docker-image
  source:
    repository: continuumio/miniconda3
    version: latest

inputs:
  - name: busywork
  - name: q2-types-channel
  - name: qiime2-channel

run:
  path: busywork/ci/master/tasks/q2-types/test.sh
